# destroy.yml
name: 'Terraform destroy on github action aws'
description: 'Destroy with terraform using remote state'
inputs:
  org_name:
    description: 'In the format of <org>'
    required: true
    default: 'md1810'
  repo_name:
    description: 'In the format of <repo>'
    required: true
    default: 'terraform-on-git-action'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.org_name }}
    - ${{ inputs.repo_name }}
